### ISSUE TITLE
Config System

### ISSUE THREAD

**Issue by buoto** [mwiniarski/balanser#4]
- Load config from file
- How to load configs in Rust and use them easily?
- Content:
```yaml
listen_address: <ip>:<port>
instances:
 - name: foo
   ip: 
   port:
```
- Handle envs/parameters to override
